FROM gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.3
FROM gcr.io/google-containers/kube-apiserver-amd64:v1.11.2
FROM gcr.io/google-containers/kube-controller-manager-amd64:v1.11.2 
FROM gcr.io/google-containers/kube-controller-manager-amd64:v1.11.2
FROM gcr.io/google-containers/kube-state-metrics-amd64:v1.3.1

MAINTAINER truewht@hotmail.com
 
